#!/bin/bash


# Args
CHANNEL=${CHANNEL:-"##pivo"}
SERVER=${SERVER:-"irc.freenode.org"}
NICK=${NICK:-"cobuduzrat"}
IRCDIR=${IRCDIR:-"ircdir"}
TMPFILE=$(mktemp)
WEBSERVER="http://blaskovic.sk:8099/?menu="

trap SIGINT "echo '/quit' > $IRCDIR/$SERVER/in"

# ii
set -x
make -C ii
rm -rfv "$IRCDIR/$SERVER"
set +x
./ii/ii -i "$IRCDIR" -s "$SERVER" -n "$NICK" &
sleep 5
echo "/j $CHANNEL" > "$IRCDIR/$SERVER/in"

sleep 2

# Parser
echo > "$IRCDIR/$SERVER/$CHANNEL/out"
tail -f "$IRCDIR/$SERVER/$CHANNEL/out" | \
    while read -r date time nick mesg; do
        nick="${nick#<}"
        nick="${nick%>}"
        echo "$mesg" | grep -q ^menu
        if [ $? -eq 0 ]
        then
            # We want menu! # strip whitespace needed!
            menu=$(echo "$mesg" | sed "s/menu //" | sed -e 's/[^-a-z0-9]//g')

            out=$(curl "${WEBSERVER}$menu")
            echo "$out"
            echo "$out" > "$IRCDIR/$SERVER/$CHANNEL/in"
        fi
    done


# End
rm $TMPFILE
