#!/bin/bash
URL="http://www.a-sporthotel.cz/menu/"
tmp=$(mktemp -d)

wget -q "$URL" -O $tmp/index.html

TODAY=$(LC=C date "+%A")

case "$TODAY" in
Monday)
    TODAY_CZ="Pondělí"
    ;;
Tuesday)
    TODAY_CZ="Úterý"
    ;;
Wednesday)
    TODAY_CZ="Středa"
    ;;
Thursday)
    TODAY_CZ="Čtvrtek"
    ;;
Friday)
    TODAY_CZ="Pátek"
    ;;
*)
    echo "Dnes je $TODAY, neni menu alebo je nieco spatne."
    rm -rf "$tmp"
    exit 0
esac

grep -A 30 "$TODAY_CZ" "$tmp/index.html" | grep -v "$TODAY_CZ" > $tmp/day_parsed

while read line
do
    # Out of day section
    echo "$line" | grep -q "sipka" 2>/dev/null
    if [ $? -eq 0 ]
    then
        break
    fi

    # </td><b>? Food!
    echo "$line" | grep -q  -e "<td><b>" -e "Polévka"
    if [ $? -eq 0 ]
    then
        echo "$line" | sed -e 's/<[^>]*>//g'
    fi


done < "$tmp/day_parsed"

rm -rf "$tmp"

