#!/bin/env bash
curl -s https://www.zomato.com/cs/brno/u-kotelny-kr%C3%A1lovo-pole-brno-sever#denni_menu | grep -A1 'tmi-price\|tmi-name' | sed -e 's/<div[^>]*>//g' -e 's/^\s*//g' -e '$!N;s/\n/ /' | grep -v '^--\s*' | sed -e '$!N;s/\n/ /' -e 's/^\s*//g' -e 's/ --\s*$//g' -e 's/\s\+/ /g'
