#!/usr/bin/env python2

import time
import urllib2
import re
from BeautifulSoup import BeautifulSoup

url = 'http://www.liquidbread.cz/liquidbread/liquidbread/mainmenu/daily-menu/'

response = urllib2.urlopen(url)
html = response.read()

soup = BeautifulSoup(html)
div = soup.findAll('div')[7]

pre = div.find('pre').prettify()
notag = re.sub('<.*?>', ' ', pre).strip()


filtered = filter(lambda x: x is not ' ', notag.split('\n'))

today = time.strftime("%a")

if today == 'Mon':
    start = 0
elif today == 'Tue':
    start = 4
elif today == 'Wed':
    start = 8
elif today == 'Thu':
    start = 12
elif today == 'Fri':
    start = 16

end = start + 4
for i in filtered[start:end]:
    print i
