#!/usr/bin/env python
# vim: set ts=2 sw=2 et fileencoding=utf-8:

import urllib2
import re
import sys
try: 
  from BeautifulSoup import BeautifulSoup
except ImportError:
  from bs4 import BeautifulSoup
reload(sys)

sys.setdefaultencoding('utf-8')

response = urllib2.urlopen('http://www.restaurant-padowetz.cz/poledni-menu.htm')
html = response.read()
parsed_html = BeautifulSoup(html)
menu = parsed_html.body.find('div', attrs={'class':'tydeniMenu '})
print('Restaurant & Pub Padowetz')
print('Polévky:')
for line in menu.find('table', attrs={'class':'jidelnicek', 'id':'t_Polevky'}):
  for cell in line:
    if re.match(r'^nazev[0-9]+.*', cell.attrs[0][1]):
        print(re.sub('\([^)]+\)', '', cell.text).strip())

print('Hlavní chod:')
for line in menu.find('table', attrs={'class':'jidelnicek', 'id':'t_Hlavni-chod'}):
  for cell in line:
    if re.match(r'^nazev[0-9]+.*', cell.attrs[0][1]):
      nazev =  re.sub('\([^)]+\)', '', cell.text).strip()
    if re.match(r'^cena[0-9]+.*', cell.attrs[0][1]):
      cena = cell.text

  if not re.match(r'.*alergen.*', nazev):
    print('{} - {}'.format(nazev.encode('utf-8'), cena.encode('utf-8')))
