#!/bin/bash
echo "U hodnyho psa"
URL="http://www.uhodnyhopsa.cz/"
tmp=$(mktemp -d)

wget -q "$URL" -O $tmp/index.html

doc=$(grep -i "doc/.*.pdf" $tmp/index.html | head -n 1 | awk -F'"' '{print $2}')

wget -q "$URL/$doc" -O $tmp/pes.pdf
pdftotext $tmp/pes.pdf

TODAY=$(LC=C date "+%A")

case "$TODAY" in
Monday)
    TODAY_CZ="Pondělí"
    ;;
Tuesday)
    TODAY_CZ="Úterý"
    ;;
Wednesday)
    TODAY_CZ="Středa"
    ;;
Thursday)
    TODAY_CZ="Čtvrtek"
    ;;
Friday)
    TODAY_CZ="Pátek"
    ;;
*)
    echo "Dnes je $TODAY, neni menu alebo je nieco spatne."
    rm -rf "$tmp"
    exit 0
esac

while read line; do
    echo "$line" | grep -q -P "^[[:space:]]*($TODAY_CZ|[0-9])"
    if [[ $? -eq 0 ]]; then
        echo "$line"
    else
        break;
    fi
done <<< "$(awk "/$TODAY_CZ/,0" "$tmp/pes.txt")"

rm -rf "$tmp"
