#!/bin/bash
echo "Na Purkynce"
TODAY=$(LC=C date "+%A")

case "$TODAY" in
Monday)
    TODAY_CZ="PONDĚLÍ"
    ;;
Tuesday)
    TODAY_CZ="ÚTERÝ"
    ;;
Wednesday)
    TODAY_CZ="STŘEDA"
    ;;
Thursday)
    TODAY_CZ="ČTVRTEK"
    ;;
Friday)
    TODAY_CZ="PÁTEK"
    ;;
*)
    echo "Dnes je $TODAY, neni menu alebo je nieco spatne."
    rm -rf "$tmp"
    exit 0
esac

PATTERN="/<div>$TODAY_CZ/,/\&nbsp\;/"
curl -s http://www.napurkynce.cz/denni-menu/ | awk "$PATTERN" | sed 's/<[^>]*>//g' | sed '$d;'
