#!/bin/bash
echo "Na Purkynce"
TODAY=$(LC=C date "+%A")

case "$TODAY" in
Monday)
    TODAY_CZ="PONDĚLÍ"
    END_PATTERN="<p>\&nbsp\;<\/p>"
    ;;
Tuesday)
    TODAY_CZ="ÚTERÝ"
    END_PATTERN="<p>\&nbsp\;<\/p>"
    ;;
Wednesday)
    TODAY_CZ="STŘEDA"
    END_PATTERN="<p>\&nbsp\;<\/p>"
    ;;
Thursday)
    TODAY_CZ="ČTVRTEK"
    END_PATTERN="<p>\&nbsp\;<\/p>"
    ;;
Friday)
    TODAY_CZ="PÁTEK"
    END_PATTERN="<p style=\"width: 100%; text-align: right; padding-bottom: 0px;\">"
    ;;
*)
    echo "Dnes je $TODAY, neni menu alebo je nieco spatne."
    rm -rf "$tmp"
    exit 0
esac

PATTERN="/<span style=\"text-decoration: underline;\">$TODAY_CZ/,/$END_PATTERN/"
curl -s http://www.napurkynce.cz/denni-menu/ | awk "$PATTERN" | sed 's/<[^>]*>//g' | sed 's/\&nbsp\;//g'
